In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns



In [18]:
df = pd.read_csv("C:\\Users\\ankit bharti\\Desktop\\ml\\Social_Network_Ads.csv")

In [19]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [21]:
df.describe

<bound method NDFrame.describe of       User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]>

In [22]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [23]:
df.keys

<bound method NDFrame.keys of       User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]>

In [24]:
df.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [25]:
df['Purchased'].value_counts()

0    257
1    143
Name: Purchased, dtype: int64

In [26]:

X = df.iloc[:, [2, 3]].values
y = df.iloc[:, 4].values

In [27]:
X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [28]:
from sklearn.model_selection  import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 10)

# Feature Scalling

In [29]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)


In [30]:
X_train


array([[-9.38945183e-01,  2.60499518e-01],
       [-9.38945183e-01,  4.33270017e-01],
       [ 3.17707601e-01,  5.89339367e-02],
       [ 2.15435398e+00, -1.03527922e+00],
       [ 8.01035595e-01,  3.46884767e-01],
       [ 8.97701194e-01, -1.03527922e+00],
       [-4.55617189e-01, -2.74513125e-02],
       [-1.13227638e+00, -1.58238580e+00],
       [-1.65620393e-01,  2.13217992e+00],
       [-2.62285991e-01, -9.20098888e-01],
       [-6.48948387e-01, -1.49600055e+00],
       [ 1.38102919e+00,  1.26832743e+00],
       [-3.58951590e-01, -7.76123472e-01],
       [-1.22894198e+00,  2.89294601e-01],
       [ 1.47769479e+00,  5.89339367e-02],
       [ 7.04369997e-01, -1.26563988e+00],
       [-6.89547938e-02, -4.88172642e-01],
       [ 2.15435398e+00,  9.22786429e-01],
       [-5.52282788e-01,  1.35471267e+00],
       [ 4.14373200e-01,  2.89294601e-01],
       [ 1.09103239e+00, -9.77689054e-01],
       [ 8.97701194e-01, -1.43841038e+00],
       [ 1.18769799e+00, -9.77689054e-01],
       [-2.

In [31]:
y_train

array([0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1], d

# Model buiding


# DecisionTreeClassifier

In [50]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
tree= DecisionTreeClassifier(criterion='entropy',random_state=0)
tree.fit(X_train,y_train)

y_pred=tree.predict(X_test)

print("testing accuracy",accuracy_score(y_test,y_pred))


testing accuracy 0.86


# LogisticRegression

In [51]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
logist= LogisticRegression(random_state=0)
logist.fit(X_train,y_train)
y_pred=logist.predict(X_test)



print("testing accuracy",accuracy_score(y_test,y_pred))


testing accuracy 0.88


# RandomForestClassifier

In [52]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
forest= RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
forest.fit(X_train,y_train)
y_pred=forest.predict(X_test)

print("testing accuracy",accuracy_score(y_test,y_pred))

testing accuracy 0.87


# Neural_network  MLPClassifier

In [55]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
nueral=MLPClassifier(hidden_layer_sizes=(10,10,10),max_iter=100)

nueral.fit(X_train,y_train)
y_pred=nueral.predict(X_test)

print("testing accuracy",accuracy_score(y_test,y_pred))

testing accuracy 0.94


C:\Users\ankit bharti\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


# Accuracy of neural network classifier 94% maximum among all four models

# Probability

In [57]:
nueral.predict_proba(X_test)

array([[0.71382295, 0.28617705],
       [0.84149687, 0.15850313],
       [0.4024765 , 0.5975235 ],
       [0.35837501, 0.64162499],
       [0.95585059, 0.04414941],
       [0.13240565, 0.86759435],
       [0.8233356 , 0.1766644 ],
       [0.34880367, 0.65119633],
       [0.91305776, 0.08694224],
       [0.8007091 , 0.1992909 ],
       [0.76497722, 0.23502278],
       [0.55225018, 0.44774982],
       [0.09500641, 0.90499359],
       [0.14301258, 0.85698742],
       [0.35995845, 0.64004155],
       [0.8236195 , 0.1763805 ],
       [0.86781749, 0.13218251],
       [0.94536912, 0.05463088],
       [0.94895675, 0.05104325],
       [0.18705237, 0.81294763],
       [0.94383259, 0.05616741],
       [0.94380685, 0.05619315],
       [0.80801699, 0.19198301],
       [0.11294363, 0.88705637],
       [0.13165562, 0.86834438],
       [0.8962651 , 0.1037349 ],
       [0.87229529, 0.12770471],
       [0.12940013, 0.87059987],
       [0.26698917, 0.73301083],
       [0.8936768 , 0.1063232 ],
       [0.

In [58]:
y_pred

array([0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0], dtype=int64)